SW_ROOT=../../..

BENCH_LIB_PATH 		= $(SW_ROOT)/libs/bench_lib
BENCH_LIB_NAME		= bench_lib.a
BENCH_LIB	 	= $(BENCH_LIB_PATH)/$(BENCH_LIB_NAME)

BENCH_LIB_FILES		= 

BENCH_OBJ 		= 

include $(SW_ROOT)/ref/common.mk
