SW_ROOT=../../..

BENCH_LIB_PATH 		= $(SW_ROOT)/libs/bench_lib
BENCH_LIB_NAME		= bench_lib.a
BENCH_LIB	 	= $(BENCH_LIB_PATH)/$(BENCH_LIB_NAME)

BENCH_LIB_FILES		= bf_skey.c bf_enc.c bf_cfb64.c

BENCH_OBJ 		= bf_skey.o bf_enc.o bf_cfb64.o

include $(SW_ROOT)/ref/common.mk
